# https://dart.dev/guides/language/analysis-options

include: package:flutter_lints/flutter.yaml
analyzer:
 errors:
  unused_import: error
linter:
 rules:
  avoid_print: false
  prefer_single_quotes: true
  always_use_package_imports: true
