name: woless
description: 'A new Flutter project.'
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
 sdk: '>=3.2.0 <4.0.0'
dependencies:
 flutter:
  sdk: flutter
 cupertino_icons: ^1.0.2
 smooth_page_indicator: ^1.1.0
 carousel_slider: ^4.2.1
 google_fonts: ^6.1.0
 flutter_launcher_icons: ^0.13.1
 iconsax: ^0.0.8
 get: ^4.6.6
 flutter_rating_bar: ^4.0.1
 intl: ^0.18.1
 flutter_html: ^3.0.0-beta.2

flutter_launcher_icons:
 android: 'launcher_icon'
 ios: true
 image_path: 'assets/icons/logo.png'
 min_sdk_android: 21 # android min sdk min:16, default 21
 web:
  generate: true
  image_path: 'assets/icons/logo.png'
  # background_color: "#hexcode"
  # theme_color: "#hexcode"
 windows:
  generate: true
  image_path: 'assets/icons/logo.png'
  icon_size: 48 # min:48, max:256, default: 48
 macos:
  generate: true
  image_path: 'assets/icons/logo.png'

dev_dependencies:
 flutter_test:
  sdk: flutter
 flutter_lints: ^3.0.1
flutter:
 uses-material-design: true
 assets:
  - assets/images/ # https://flutter.dev/assets-and-images/#resolution-aware
  - assets/images/sample/
  - assets/icons/
  - assets/avatar/
 # fonts:
 #   - family: Schyler
 #     fonts:
 #       - asset: fonts/Schyler-Regular.ttf
 #       - asset: fonts/Schyler-Italic.ttf
 #         style: italic
 #   - family: Trajan Pro
 #     fonts:
 #       - asset: fonts/TrajanPro.ttf
 #       - asset: fonts/TrajanPro_Bold.ttf
 #         weight: 700
 # see https://flutter.dev/custom-fonts/#from-packages
